# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SocialActivity
                                 A QGIS plugin
 Plot Social Activity around a supplied point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-03
        copyright            : (C) 2019 by Vincenzo Lanzaro - SimplySoftware.co
        email                : vl@simplysoftware.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SocialActivity class from file SocialActivity.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .social_activity import SocialActivity
    return SocialActivity(iface)
